### ISSUE TITLE
Filter chips 

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#10]
[Filter chips](https://m3.material.io/components/chips/guidelines#8d453d50-8d8e-43aa-9ae3-87ed134d2e64) to be able to filter the used software clientside by topics e.g. it should be possible to filter for "cooperation" on [publish](https://it-at-m.github.io/opensource.muenchen.de/publish.html)

**Comment by FabianWilms** [comment]
done with https://github.com/it-at-m/opensource.muenchen.de/commit/314ce3ada707585899f0214bdf93343f0094b95f
