### ISSUE TITLE
Sorting Software

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#11]
When it comes to [self-developed](https://it-at-m.github.io/opensource.muenchen.de/publish.html) projects, some sofware (e.g. digiwf) is said to be at the top of the list, currently it's alphabetically. 

Lets add a "priority" to the frontmatter and sort it by priority first and alphabetically second!

**Comment by FabianWilms** [comment]
What is the preferred sorting rule here?

Currently it's alphabetically. Do you want to add a "priority" to the frontmatter and sort it by priority first and alphabetically second?

**Comment by klml** [comment]
@FabianWilms you are right, I just improved my description.

**Comment by FabianWilms** [comment]
done 

https://it-at-m.github.io/opensource.muenchen.de/publish.html#overview
