### ISSUE TITLE
edit this page

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#12]
A link on ever singe page to the corresponding source file (e.g. [use](https://github.com/it-at-m/opensource.muenchen.de/blob/main/use.md), to allow easier enhancements (with PRs)

**Comment by FabianWilms** [comment]
Hint: https://vitepress.dev/reference/default-theme-edit-link#site-level-config

**Comment by klml** [comment]
I linked the detail page, 
https://github.com/it-at-m/opensource.muenchen.de/blob/main/de/publish.md

not the edit link
https://github.com/it-at-m/opensource.muenchen.de/edit/main/de/publish.md

When you are not logedin on github , github forces you on the "Sign in to GitHub"-Page, imho thats  missleading.

Should we change the `text: 'See  and edit this page on GitHub'`?

**Comment by FabianWilms** [comment]
> I linked the detail page,  not the edit link

Yes that's better 👍 
 
> Should we change the `text: 'See and edit this page on GitHub'`?

Maybe only `View this page on GitHub`
