### ISSUE TITLE
[Bug] wrong links in lists

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#169]
# Problem

links in lists lead to the wrong page

e.g. https://opensource.muenchen.de/de/use.html 7-Zip leads to dave
```

<a class="...." style="" href="/de/software/dave.html" data-v-8569d21e="">
....
<div class="v-responsive v-img" style="" aria-label="DAVe logo" role="img" data-v-963839fb="">
.....
<span style="overflow:hidden;text-overflow:ellipsis;" data-
v-8569d21e="">7-Zip</span>
```

# Reproduce locally

1. npm run docs:build
2. npm run docs:preview
3. Open directly via link: http://localhost:4173/use.html

~~Cant reproduce on localhost, but on https://opensource-test.muenchen.de/de/use.html~~

similar to #136

**Comment by FabianWilms** [comment]
This seems to only happen when linking directly to a sub-page. If you navigate to a different page and back, the data is available.

It seems like vitepress has a problem here loading the correct data. What i find weird is the fact, that the title and logos are being loaded correctly, but the teaser and link seem to be broken.

**Comment by FabianWilms** [comment]
@klml I managed to reproduce it locally by building the docs and opening the preview. I added this in the issue description.

**Comment by FabianWilms** [comment]
Further investigation: It can't be a problem with loading the data, as vitepress embeds all of it into the final js-File:

https://opensource.muenchen.de/assets/chunks/TagTile.Bo5ZdVHW.js

**Comment by FabianWilms** [comment]
I noticed the following log in the browser console:

> Hydration completed but contains mismatches.

This is an error of the server side rendering. Trying to fix the bug by adding the `<ClientOnly>`-Tags around our dynamic components.

**Comment by FabianWilms** [comment]
> Trying to fix the bug by adding the <ClientOnly>-Tags around our dynamic components.

This works, currently setting up a PR.
