### ISSUE TITLE
sidebar: false does not work

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#17]
```
---
sidebar: false
---
```
from  https://raw.githubusercontent.com/it-at-m/opensource.muenchen.de/main/use.md

But the sidebar is still in place (e.g. https://it-at-m.github.io/opensource.muenchen.de/use.html )

**Comment by FabianWilms** [comment]
It does work, but t's not what you want it to be ;)

![image](https://github.com/it-at-m/opensource.muenchen.de/assets/10800158/caeaa389-cb95-4522-97c6-e9e814046f23)

The red part is the sidebar (which is not visible), the green part ist part of the rendered document. I'm currently searching for a way to disable it.

**Comment by klml** [comment]
@FabianWilms for this hint ;) its [aside](https://vitepress.dev/reference/frontmatter-config#aside) and [works](https://it-at-m.github.io/opensource.muenchen.de/impress)!


But is this [sidebar: false in eg use](https://raw.githubusercontent.com/it-at-m/opensource.muenchen.de/main/use.md) useless?

**Comment by FabianWilms** [comment]
As we currently have [no sidebar defined](https://github.com/it-at-m/opensource.muenchen.de/blob/main/.vitepress/config.mts#L35) it doesn't really make a difference
