### ISSUE TITLE
Translate tags too

### ISSUE THREAD

**Issue by MrSebastian** [it-at-m/opensource.muenchen.de#20]
The tags are currently only in one language:

![grafik](https://github.com/it-at-m/opensource.muenchen.de/assets/13592751/5762366a-4b4e-4c22-b901-012e526db05b)  
*Tags listed in the english version of the use page*

I suggest to translate them too. We could use a lookup table for the tags for each language. If it has an entry the translated version is picked. When there is no entry for the selected language the native value is shown.

---

I am not sure if it is really necessary right now, because most of the tags should be readable (except `eigentwickung` oder `schnittstelle`).

**Comment by klml** [comment]
@MrSebastian you are right, this is el bit mixed. we should use one language for tags, imho english.

So I suggest to translate eigenentwicklung with "inhouse" and schnittstelle with "interface".

> I suggest to translate them too. We could use a lookup table for the tags for each language. If it has an entry the translated version is picked. When there is no entry for the selected language the native value is shown.

Thats a good enhancement.

**Comment by MrSebastian** [comment]
next step is to refactor all existing tags:
- `eigenentwicklung` ->`inhouse`
- `infrastruktur` -> `infrastructure`
- `kooperation` -> `cooperation`
- `refarchinfrastruktur` -> `refarchinfrastructure`
- `schnittstelle` -> `interface`
- `webanwendung` -> `webapp`

I guess I can do it til the end of the week.

@FabianWilms @klml are there any other issues and branches that may produce a conflict?

**Comment by FabianWilms** [comment]
I think most of these are already fixed in #28 

There are currently two branches that were not merged becaues of this feature in which it should be integrated afterwords:

- https://github.com/it-at-m/opensource.muenchen.de/tree/21-software-overview-own-page
- https://github.com/it-at-m/opensource.muenchen.de/tree/22-show-tags-on-software-detail-page

**Comment by FabianWilms** [comment]
It's done 👏
