### ISSUE TITLE
software overview: own page

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#21]
Build an own page for the [general overview](https://it-at-m.github.io/opensource.muenchen.de/use.html#overview) 

Use taglist with three additional tags: use, improve, publish

**Comment by FabianWilms** [comment]
> Use taglist with three tags: use, improve, publish

should we really only use these three tags? and retag all other articles?

also: https://github.com/it-at-m/opensource.muenchen.de/issues/23

When you want to link to a predefinced selection of tags this would not work.

**Comment by FabianWilms** [comment]
initial on https://github.com/it-at-m/opensource.muenchen.de/tree/21-software-overview-own-page

waiting for #25 to include i18n to integrate it here, too.

**Comment by klml** [comment]
@FabianWilms 

> should we really only use these three tags? and retag all other articles?

Yes, but with three _additional_ tags: use, improve, publish

> When you want to link to a predefinced selection of tags this would not work.

Why? `const selectedFilters = ref(['use', 'improve', 'publish'])` worked for me

**Comment by FabianWilms** [comment]
> Why?

I was referring to using **only** those three tags. When you want to add additional tags this will of course work.
