### ISSUE TITLE
Difficult to read text on home in Dark Mode

### ISSUE THREAD

**Issue by DirkGernhardt** [it-at-m/opensource.muenchen.de#39]
> Munich Open Source - More transparency from our IT

difficult to read in front of the ferris wheel

**Comment by FabianWilms** [comment]
add style for .container .main .text --> no transparency in `color`

**Comment by DirkGernhardt** [comment]
![image](https://github.com/it-at-m/opensource.muenchen.de/assets/67147140/c101f962-6398-42f0-aac8-6d6021576b1c)
