### ISSUE TITLE
Complete translation Contribution

### ISSUE THREAD

**Issue by DirkGernhardt** [it-at-m/opensource.muenchen.de#41]
Translation of Contribution/financing is missing.

**Comment by klml** [comment]
@DirkGernhardt https://it-at-m.github.io/opensource.muenchen.de/contribute.html#funding

**Comment by DirkGernhardt** [comment]
Link to wikipedia should be to the english version: https://en.wikipedia.org/wiki/Business_models_for_open-source_software

**Comment by klml** [comment]
@DirkGernhardt https://it-at-m.github.io/opensource.muenchen.de/improve.html#funding
