### ISSUE TITLE
GRIP is not published

### ISSUE THREAD

**Issue by DirkGernhardt** [it-at-m/opensource.muenchen.de#45]
The planning tool GRIP is not published but we use the therefore the Tool Nuclos https://de.wikipedia.org/wiki/Nuclos

**Comment by klml** [comment]
@DirkGernhardt we have https://it-at-m.github.io/opensource.muenchen.de/software/grip, but I suggest we should rename it to Nuclos

**Comment by klml** [comment]
https://it-at-m.github.io/opensource.muenchen.de/software/nuclos
