### ISSUE TITLE
software/ title from frontmatter.application

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#53]
Currently software detail pages like [digiwf](https://it-at-m.github.io/opensource.muenchen.de/software/digiwf.html) use the generic page title (`    <title>Munich Open Source | Munich Open Source</title>`).

frontmatter.application should be better

**Comment by klml** [comment]
Its possible to use [vitepress frontmatter-config#titletemplate](https://vitepress.dev/reference/frontmatter-config#titletemplate)

* no code changes needed 👍 
* `titleTemplate` is missleading over `application` 👎

**Comment by klml** [comment]
@FabianWilms whats your opinion about using standard [vitepress frontmatter-config#titletemplate](https://vitepress.dev/reference/frontmatter-config#titletemplate)?

**Comment by FabianWilms** [comment]
I think it would be the best solution to only using the `title`-Tag in Frontmatter. `titletemplate` only changes the suffix and that can stay as `| Munich Open Source` imo.
