### ISSUE TITLE
mobile LHM Logo is squished

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#55]
![grafik](https://github.com/it-at-m/opensource.muenchen.de/assets/295778/913390e0-1731-49d5-8f24-c722e23c2cba)

## possible Solutions

* resize 
 * just use the Kindl without "Landeshauptstadt München" (like https://pflege-in-muenchen.de/)

**Comment by klml** [comment]
@FabianWilms please review my hackihack 2be4bbd

**Comment by FabianWilms** [comment]
> @FabianWilms please review my hackihack [2be4bbd](https://github.com/it-at-m/opensource.muenchen.de/commit/2be4bbd78bb351f8427c25ce58cdfa1072d9a018)

Works well 👍
