### ISSUE TITLE
chips/tags in dark-mode not readable

### ISSUE THREAD

**Issue by eidottermihi** [it-at-m/opensource.muenchen.de#7]
![image](https://github.com/it-at-m/opensource.muenchen.de/assets/2780736/9b8405b8-d52c-49af-b7e5-4043d7cd18ea)

**Comment by FabianWilms** [comment]
I'm in the process of trying to add vuetify to this site so that we can use their components inside some articles. This will be adressed as well when I've made some progress 👍
