### ISSUE TITLE
redirects without trailing slash

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#75]
Currently we use trailing slash

https://opensource.muenchen.de/de/

we should support slash (as in redirect) without trailing slash

https://opensource.muenchen.de/de

**Comment by FabianWilms** [comment]
https://vitepress.dev/guide/routing#route-rewrites

**Comment by FabianWilms** [comment]
> This is expected. Missing trailing slash requires special handling in deployment server (e.g. Netlify does this by default), not from VitePress.

*from https://github.com/vuejs/vitepress/issues/490#issuecomment-1013716466*

So probably it's easier for us to do this:

https://timmehosting.de/blog/nginx-trailing-slash-zu-urls-hinzufuegen-rewrite-rule

**Comment by FabianWilms** [comment]
https://opensource.muenchen.de/de working now @klml
