### ISSUE TITLE
Infobox 

### ISSUE THREAD

**Issue by klml** [it-at-m/opensource.muenchen.de#9]
Create an Infobox with keyfacts (e.g. code repo, licence etc) from front matter data (e.g. [digiwf.md](https://raw.githubusercontent.com/it-at-m/opensource.muenchen.de/main/software/digiwf.md))

**Comment by FabianWilms** [comment]
is integrated.

@klml do you mind if I change the design a little bit?

**Comment by FabianWilms** [comment]
| Before | After
| --- | --- |
| ![image](https://github.com/it-at-m/opensource.muenchen.de/assets/10800158/403eec40-dcfc-4b6e-9d8c-fd5a4b5818d5) | ![image](https://github.com/it-at-m/opensource.muenchen.de/assets/10800158/61e24f4b-8375-40c8-8408-e0e7de40275a) |
| 
| ![image](https://github.com/it-at-m/opensource.muenchen.de/assets/10800158/60573954-b9fd-4026-9788-718c2e4f7559) | ![image](https://github.com/it-at-m/opensource.muenchen.de/assets/10800158/6842d4ae-fb04-48c8-929b-f22247545fce) |

**Comment by FabianWilms** [comment]
Now with mobile version 

![image](https://github.com/it-at-m/opensource.muenchen.de/assets/10800158/fa137b5f-71b1-477b-98cf-be04b0f77b5a)

**Comment by FabianWilms** [comment]
@klml if you like the current version you can close this issue

**Comment by klml** [comment]
@FabianWilms everything is fine. I just allowed to use logo_and_ screenshot (eg [geoportal.html](https://it-at-m.github.io/opensource.muenchen.de/software/geoportal.html)). OK?

**Comment by FabianWilms** [comment]
Of course! The only problem is that this breaks mobile layout:

![image](https://github.com/it-at-m/opensource.muenchen.de/assets/10800158/a75461b8-041e-4b16-bc9e-405e4d19eec8)

**Comment by klml** [comment]
@FabianWilms removing class horizontal helped, but not sure why class horizontal was introduced in the first place

**Comment by klml** [comment]
@FabianWilms we should give the logo a max width

**Comment by FabianWilms** [comment]
Becaus previously, with only the logo, it looked better in a horizontal layout on medium sized screens

![image](https://github.com/it-at-m/opensource.muenchen.de/assets/10800158/db37478b-5bad-4813-a6d7-6d8f3b8b67e9)

And I don't think the screenshot is useful in the sidebar, as there currently is no way on desktop to enlarge the screenshot. I think the (big) screenshots belong in the content area while the (small) logo fits well into the sidebar.

**Comment by klml** [comment]
> And I don't think the screenshot is useful in the sidebar, as there currently is no way on desktop to enlarge the screenshot. I think the (big) screenshots belong in the content area while the (small) logo fits well into the sidebar.


@FabianWilms you are right, i moved them
